### ISSUE TITLE
What test runners should we take into account?

### ISSUE THREAD

**Issue by afontcu** [vuejs/vue-test-utils-next-docs#6]
Can we provide configuration guides for Jest+Mocha but then just use Jest for the rest of guide?

**Comment by lmiller1990** [comment]
Sounds good - we can say we are assuming Jest at the start of the guide. Not sure we need to provide too much actual docs around configurating at all - we could just provide some repositories that are preconfigured and ready to go, as well as a vue-cli plugin.

**Comment by dobromir-hristov** [comment]
I also think keeping to Jest (its kind of standard around these days) is good.

But keeping setup guides for both is also necessary, as beginners expect this to be here, its the testing docs 😆

**Comment by afontcu** [comment]
Sure!

Let's agree on:

- Providing basic setup guides for Jest and Mocha (…and something else?)
- …and/or links to vue-cli plugins, some example repos, whatever.
- Assume Jest for the rest of the guide (trying to avoid complex stuff such as partial matches and so on)

**Comment by lmiller1990** [comment]
^ works for me!

Also I don't think beginners want to configure things (I didn't). I think we should provide a template or something, this way beginners do not need to mess with config.

Adding VTU to an existing project will always be more complex because of the unknown amount of dependencies (style loaders, languages, templating languages...).
